import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://172.17.1.112:8080/auth/realms/ris-pacs/protocol/openid-connect/auth?client_id=angular-ui&redirect_uri=http%3A%2F%2F172.17.1.112%3A8080%2F&state=85240e73-8998-48ed-871d-b63c9ddab2c8&response_mode=fragment&response_type=code&scope=openid&nonce=28abc813-6887-4b5e-8277-3763f1b58895');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('user.0');
  await page.getByRole('textbox', { name: 'Username or email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('user@0');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Worklist Archive' }).click();
  await page.getByRole('button', { name: 'Open calendar' }).click();
  await page.getByText('Last 30 days').click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('C');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca ');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca C');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca ');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca S');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca Sc');
  await page.getByText('Ca Score (Adult)').first().click();
  await page.locator('app-report-details').getByRole('link', { name: 'Worklist' }).click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca');
  await page.getByText('Range14/05/2026–').click();
  await page.getByText('Last 30 days').click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('C');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca');
  await page.getByText('Ca Score (Adult)').first().click();
  await page.getByText('Create Calcium Report').nth(1).click();
  await page.locator('app-report-details').getByRole('link', { name: 'Worklist' }).click();
  await page.getByText('Range14/05/2026–').click();
  await page.getByText('Last 30 days').click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).click();
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('C');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Patient Name/ID, Examination' }).fill('Ca');
  await expect(page.locator('tbody')).toContainText('Ca Score (Adult)');
  await page.getByRole('cell', { name: 'Ca Score (Adult) 06/05/2026' }).click();
  await page.getByText('Create Calcium Report').nth(1).click();
});